// ============================================================
// CARD DATABASE — Completo PDF oficial + extras modernas
// (extraído de cartas-contra-la-humanidad_v4.jsx)
// ============================================================
export const WHITE_CARDS = [
  // === PDF OFICIAL (páginas 3-25, ~460 cartas) ===
  "Una maldición gitana","Un minuto de silencio","Muchos tornillos y pocas tuercas","Un policía honesto sin nada que perder",
  "Hambruna","Bacteria carnívora","Víboras voladoras sexuales","Que te valgan madres los países africanos",
  "Mandar mensajitos cachondos","Cambia-formas","Estrellas porno","Violar y saquear",
  "72 vírgenes","Un comando armado disparando a un domicilio","Una paradoja del tiempo","Antojitos mexicanos",
  "Bling bling","Consultores","Deuda aplastante","Traumas con el papá",
  "Aprobado por Carlos Slim™","Tirar un candelabro sobre tus enemigos mientras subes agarrado de la cuerda","Vicente Fox","Desnudez frontal",
  "Inyecciones de hormonas","Poner un huevo","Encuerarte y ver Nickelodeon","Pretender que te importa Ridículo en público",
  "Compartir jeringas","Mocos","La inevitable muerte del universo","El milagro de dar a luz",
  "El Rapto","Sacártela","El privilegio de los blancos","Deberes matrinoniales",
  "El Ladrón de Hamburguesas","Desodorante AXE","La sangre de Cristo","Horrorosos accidentes de depilación láser",
  "¡¡¡BATMAN!!!","Agricultura","Un mongolito robusto","Selección natural",
  "Abortos con un gancho de ropa","Comerte la torta antes del recreo","La papada de López-Doriga","World of Warcraft",
  "Hacer mal tercio","Obesidad","Un equipo de volleybol homoerótico","Tetanos",
  "Un despliegue copulatorio","Torcedura testicular","Buffet de pizza por $50","Pizza de Oreo™",
  "Kalimba","Queso fundido","Ataques de velociraptor","Quitarte la camiseta",
  "Esmegma","Alcoholismo","Un hombre de mediana edad en patines","El Ataque de los Ositos Cariñositos",
  "Atragantarse y vomitar","Paletotas gigantes","Odiarse a si mismo","Niños con correas",
  "Un faje sin ganas","La Santa Biblia","Porno alemán de fetiches","Estar en llamas",
  "Embarazo adolescente","Gandhi","Dejar un mensaje de voz incómodo","Ganchos a la mandíbula",
  "Representantes de atención al cliente","Una erección que dura más de 4 horas","Mis genitales","Ligar en la clínica de abortos",
  "Ciencia","Sexo oral no recíproco","Aves que no vuelan","Una buena esnifada",
  "Tehuacanazo","Un desayuno balanceado","Universidad del Valle de Mexico","Robarle un dulce a un bebé",
  "El Teletón","Rascarte el trasero a escondidas","Post-its pasivo-agresivos","El equipo chino de gimnasia",
  "Cambiarse a axtel","Hacerse tantita pipí","El video del FUA","Emisiones nocturnas",
  "Los judíos","Mis caderas","Muslos de acero","Guiñarle a los viejitos",
  "Maestro Limpio, justo detrás de ti","Una caricia gentil en la entrepierna","Tensión sexual","La fruta prohibida",
  "Skeletor","Whiskas®","Ser rico","Dulce, dulce venganza",
  "Priistas","Un venado gaseoso","Natalie Portman","Una sobadita",
  "Pilotos kamikaze","Sean Connery","Propaganda homosexual","Los Mexicanos chambeadores",
  "Un halcón con gorrita","Monaguillos","El hombre Kool-Aid","Enojarte tanto que se te para",
  "Muestras gratis","Tanto rollo para nada","Hacer lo correcto","La venta de Texas a Estados Unidos",
  "Lactancia","Paz mundial","Robocop","Pasado de lanza",
  "Justin Bieber","Oompa-Loompas","Grito de mariachi inapropiado","Pubertad",
  "Fantasmas","Unas tetas operadas asimétricas","Decir adiós con las manos","Dedear",
  "Carlos Salinas pescandose un huevo en un gancho de la cortina","Atole con el dedo","Brutalidad Policiaca","Mario Aburto Martinez",
  "Pre-adolescentes","Revendedores","Te aguantas la risa cuando dicen papanicolaou","\"Tuitear\"",
  "Darth Vader","Que te la jalen sin ganas","Exactamente lo que esperabas","Querer eructar y terminar vomitando en el suelo",
  "Focusín™","Células madre embrionarias","Un escote con clase","Sexo Panda",
  "Lobotomía con picahielo","Tom Cruise","Herpes bucal","Cachalote",
  "Gente sin casa","Tercera base","Incesto","Pacman tragando semen sin control",
  "Un mimo teniendo un ataque al corazón","Hulk Hogan","Dios","Tallarse bajo los pliegues de carne",
  "Lluvia dorada","Emociones","Lamer cosas para decir que son tuyas","Cerveza Indio",
  "La placenta","Combustión humana espontánea","Amigos con beneficios","Pintar con los dedos",
  "El olor de los viejitos","Morirse de disentería","Mis demonios interiores","Una pistola de agua llena de pipi de gato",
  "Victoriano Huerta","Acurrucarse con tu pareja","¿Donde jugarán las niñas?","Peleas de gallo",
  "Fuego amigo","Ernesto Zedillo","Una fiesta de cumpleaños decepcionante","Una negra descarada",
  "Atletas matemáticos","Un caballo pequeño","Blue Demon","Cabalgar hacia el atardecer",
  "Un giro de trama escrito por M. Night Shyamalan","Afros","Destrucción mutuamente asegurada","Pedófilos",
  "Levadura","Robar tumbas","Comerse el último bisonte que existe","Catapultas",
  "Gente pobre","Olvidar la batalla de Puebla","Bailar country","La Fuerza",
  "Armas de destrucción masiva","El Chupacabras","Ponerle limón a todo","Crocs con calcetines",
  "Cagar con la puerta abierta","El América","Mariguanol","Venganza",
  "Comer tacos a las 3am","Dinero del Monopoly","Un striptease muy incómodo","Chairos",
  "Pedos silenciosos pero mortales","El PRI","Reggaetón","Tijuana",
  "Donald Trump","Lágrimas de cocodrilo","Un exorcismo","Socialismo",
  "El Chapo","Narcotráfico","Chespirito","Mordidas",
  "Arrepentirse","Bebés muertos","Prepucio","Solos de saxofón",
  "Italianos","Un feto","Disparar un rifle al aire mientras se la metes hasta adentro a un cerdo que está chille y chille","Andrés Manuel Lopez Obrador",
  "Amputados","Eugenesia","Mi estado de relación","Christopher Walken",
  "¿Abejas?","Novelas eróticas de Harry Potter","Universidad","Emborracharte con enjuague bucal",
  "Nazis","200 gramos de heroína","Stephen Hawking hablando sucio","Padres muertos",
  "Esperanza","El Rev. Dr. Martin Luther King, Jr.","Un micropene","Mi alma",
  "Una confusión caliente","Vikingos","Gente ardiente","Seducción",
  "Complejo de Edipo","Gansos","Calentamiento global","Música New Age",
  "Burritos","Hacer pucheros","Atropellar a alguien","Sufragio femenino",
  "Un condón defectuoso","Laura de América","Niños africanos","El incendio de la guardería ABC",
  "Aguafiestas","Pedorrearte e irte","Ser pedante con los niños","Poner trampas en la casa para detener a los ladrones",
  "Una Cama de Agua","Morirse","Huracán Katrina","Los gays",
  "La insensatez del hombre","Hombres","Los Menonitas","Huevos de pterodáctilo",
  "Ejercicios para fomentar la sinergia del Equipo","Tumor cerebral","Cartas Contra la Humanidad","El miedo mismo",
  "Lady Gaga","El lechero","Una boca sucia",
  // === CARTAS DEL PDF FALTANTES EN v3 ===
  "Limpiarle el trasero","Diseño inteligente","Bocafloja","SIDA",
  "Fotos de tetas","Super Hombres","Marta Sahagún de Fox","Gladiadores Americanos",
  "Ponerte bien pacheco","Cienciología","Envidia del pene","Quitarte lo gay rezando",
  "Retozando","Dos enanos cagando en una tina","El Ku Klux Klan","Genghis Khan",
  "Metanfetaminas","Servidumbre","Cuidarse de los extraños","Una matraca",
  "La carrera de actuación de Cuautemoc Blanco","Hacer cabriolas","Justicia por tu propia mano","Sobrecompensar",
  "Bukkake pixelado","Una vida de tristeza","Racismo","Lanzamiento de enanos",
  "Arcoiris y brillo del sol","Un chango fumando","Inundaciones repentinas","El testículo perdido de Lance Armstrong",
  "Arcadas","Los terroristas","Britney Spears a los 55 años","Actitud",
  "Empezar a cantar y bailar","Lepra","Hoyo glorioso","Traer las luces altas",
  "El corazón de un niño","¡Cachorritos!","Despertar medio desnudo en un estacionamiento","Condones",
  "La vagina de Elba Esther","El Perineo","Escuchar activamente","Limpieza étnica",
  "La Maquinita que si Pudo","La mano pachona","Esperarse hasta el matrimonio","Estupides incuantificable",
  "Perfume Euphoria™ de Calvin Klein","Regalar algo que te regalaron","Autocanibalismo","Disfunción erectil",
  "Mi colección de juguetes sexuales de alta tecnología","El Papa","Gente blanca","Porno de tentáculos",
  "Paty Chapoy vomitando a la vez que un grupo de arañas eclosiona en su cerebro y salen por sus ductos lagrimales",
  "Demasiado gel de pelo","Seppuku","Gays bailando quebradita",
  "Hacer trampa en las Olimpiadas Especiales","Carisma","Keanu Reeves","Pedro Infante",
  "Moderato","Una miradita","Cagar para adentro","Menstruación",
  "Niños con cáncer en el trasero","Una sorpresa salada","El Sur","La violación de nuestros derechos más básicos",
  "Es que no me tienes paciencia","Violar en una cita","Ser fabuloso","Necrofilia",
  "Centauros","El Tesoro del Saber","Los negros","Caballerosidad",
  "Sopa Maruchan","Perras","Los que están muy discapacitados","Huérfanos hermosos",
  "Robot Hitler","Cagar enchilado","Otra maldita película de vampiros","Slinkies enredados",
  "El verdadero significado de la Navidad","Estrógeno","Unos taquitos al vapor","La cosa que te electrocuta los abdominales",
  "Orinar una piedra del riñon","Un ano blanqueado","Michael Jackson","Mejoras cibernéticas",
  "Chavos que no te hablan después de la primera cita","Calzones con rajita de canela","Masturbación","Hablar como fresa",
  "Pedos vaginales","Esconder una erección","Calzones comestibles","Viagra®",
  "Sopa muy caliente","Muhammad (Alabado Sea)","¡Sexo Sorpresa!","Una orden de tacos",
  "Tomar solo","Dedos de pito","Múltiples heridas con navaja","Hacerte popo",
  "Abuso infantil","Perlas anales","Muertes civiles","Sacarla",
  "Robert Downey, Jr.","Carne de caballo","Un sombrero muy chido","Kim Jong-il",
  "Un vello púbico fuera de lugar","Pandilleros fresas","Los cholos","Metérsela por detrás",
  "Alimentar al Botija","Enseñarle a un robot a amar","Unos chingazos","Un molino lleno de cadáveres",
  "Conde Patula","Usar los calzones al revés para no lavarlos","El rayo de la muerte","Techo de espejo",
  "Una hielera llena de órganos","El Sueño Americano","Tomarse una caguama de jilo","Cuando te echas un pedo y se te cagas un poquito",
  "Permanencia del objeto","Pulgares opuestos","Examenes de Admisión","Parloteo",
  "Manos de sierra eléctrica","Nicolas Cage","Concursos de belleza infantil","Explosiones",
  "Esnifar pegamento","Peña Nieto en el desierto con buitres dándole vueltas","Represión","Rufies",
  "Mi vagina","Pantalones con un agujero en el trasero","Un homicidio muy sucio","Dar el 110%",
  "Su Majestad, la Reina Elizabeth II","La Noche Triste","Ser marginalizado","Duendes",
  "Barack Obama","Asiáticos que no son buenos para las matemáticas","Hombres japoneses viejitos","Intercambiar cordialidades",
  "Heteronormatividad","Partir el mar rojo","Arnold Schwarzenegger","Que te la chupen cuando manejas",
  "Abdominales espectaculares","Pudín de higos","Un león de zoológico tristón","Una bolsa de frijoles mágicos",
  "Malas decisiones de vida","Mi vida sexual","Auschwitz","Una tortuga mordiendote la puntita del pene",
  "Una detonación termonuclear","El clítoris","El Big Bang","Minas terrestres",
  "Amigos que se comen toda la botana","Cabras comiendo latas","La Danza del Hada de Azúcar","Jalartela en una alberca llena de lágrimas de niños",
  "Carne de hombre","Tiempo para mi mismo","El metro subterráneo","Decir chistes del Holocausto en un mal momento",
  "Un mar de problemas","Sueños guajiros","La voz de Morgan Freeman","Mujeres en comerciales de yogurt",
  "Aumento de tamaño natural para el caballero","Ser un hechicero de putamadre","Piercings genitales","Trasvestis pasables",
  "Peleas sexy con almohadas","Pelotas","La abuela","Fricción",
  // === CARTAS EXTRA MODERNAS (Edición México actualizada) ===
  "El audio de Layda Sansores","ChatGPT","El peso mexicano devaluándose","Bad Bunny",
  "Tiktokers haciendo challenges pendejos","La fila del SAT","Un Only Fans de tu tía","Los baches de la CDMX",
  "Sheinbaum en conferencia mañanera","Netflix subiendo precios otra vez","Una quesadilla sin queso","El WiFi del vecino",
  "Maruchan con Valentina","Los XV años de tu prima","Un viernes de quincena","El outfit de Weight a Nodal",
  "Tu ex stalkeándote en Instagram","El algoritmo de TikTok","Un uber que cancela a 2 minutos","Ghostear después de la primera cita",
  "Memes del América perdiendo","El trenecito en la peda","Un mural de Rivera pero con reggaetón","Perreo hasta el suelo",
  "La letra chiquita de Telcel","Influencers vendiendo té para bajar de peso","El metro a las 7am","Crypto bros",
  "La señora de las quesadillas afuera del estadio","Red flags que ignoras","Situationship","Dejar en visto",
  "Tu mamá mandando stickers de Buenos Días","Un Oxxo en cada esquina","La rosca de reyes con un solo muñeco","El WiFi de Infinitum cayéndose",
  "Tacos de canasta a las 6am","El grito de un vendedor ambulante","Tepito","La cuesta de enero",
  "Pedir fiado en la tiendita","Echar la hueva en domingo","Un mezcal artesanal","El clásico América vs Chivas",
  "Mandar audios de 5 minutos por WhatsApp","Tu jefe mandando mensajes a las 11pm","La Llorona","El chismógrafo del trabajo",
  "Hacer fila 3 horas en el IMSS","Un elote con todo","Vender Herbalife","La chancla de tu mamá",
  "Uber Eats a las 2am","El novio de tu hermana","Llegar tarde a todo","El 'ahorita' mexicano que significa nunca"
];

export const BLACK_CARDS = [
  // === PDF OFICIAL (páginas 26-30, ~90 cartas) ===
  {text:"Ahora se prohíbe _ en los aviones.",pick:1},{text:"Es una pena que los niños de ahora se involucren en _.",pick:1},
  {text:"En 1,000 años, cuando el dinero en papel solo sea una memoria lejana, _ va a ser nuestra moneda nacional.",pick:1},
  {text:"La Federacion Mexicana de Futbol ahora prohíbe _ porque les da una ventaja injusta a los jugadores.",pick:1},
  {text:"¿Qué placer culpable tiene Batman?",pick:1},{text:"El siguiente libro de J.K. Rowling: Harry Potter y la Cámara de _.",pick:1},
  {text:"Así es, maté a _. ¿Cómo, preguntas? _.",pick:2},{text:"Discuple maestro, no acabé la tarea porque _.",pick:1},
  {text:"Y el Oscar a _ va para _.",pick:2},{text:"Para mi siguiente truco, sacaré un _ de _.",pick:2},
  {text:"_ + _ = _.",pick:3},{text:"¿Qué traje de regreso de mis vacaciones?",pick:1},
  {text:"¿_? Hay una aplicación para eso.",pick:1},{text:"Paso 1: _. Paso 2: _. Paso 3: ¡Dinero!",pick:2},
  {text:"_. ¡A que uno no te basta!",pick:1},{text:"¿Cuál es mi anti-droga?",pick:1},
  {text:"Mientras que los Estados Unidos competían contra la Unión Soviética para llegar a la luna, el Gobierno Mexicano gastaba millones de pesos en investigación para _.",pick:1},
  {text:"En una nueva telenovela de Televisa, Belinda tiene problemas con _ por primera vez.",pick:1},
  {text:"¿Cuál es mi poder secreto?",pick:1},{text:"¿Cuál es la nueva dieta maravilla?",pick:1},
  {text:"¿Qué es lo que cenaba El Santo?",pick:1},{text:"Cuando el Faraón no reaccionó, Moisés invocó una Plaga de _.",pick:1},
  {text:"¿Cómo mantengo el fuego en mi relación amorosa?",pick:1},{text:"¿Qué es lo más crujiente?",pick:1},
  {text:"Cuando me malviajaba con peyote, _ se convirtió en _.",pick:2},
  {text:"En la cárcel, dicen que puedes cambiar 200 cigarros por _.",pick:1},
  {text:"Después del terremoto, Niurka les llevó _ a los Haitianos.",pick:1},
  {text:"Santa Clos ahora les da _ a los niños en vez de carbón.",pick:1},
  {text:"La vida de los Indígenas cambió para siempre cuando los Españoles les trajeron _.",pick:1},
  {text:"¿Qué utiliza la SEP para motivar a los niños a estudiar?",pick:1},
  {text:"Quizá lo trae de nacimiento. Quizá tiene _.",pick:1},
  {text:"En los últimos momentos, Michael Jackson pensó en _.",pick:1},
  {text:"A la gente blanca le gusta _.",pick:1},{text:"_ te lleva fácilmente a _.",pick:2},
  {text:"¿Porqué me duele todo?",pick:1},
  {text:"Una cena romántica a la luz de las velas no estaría completa sin _.",pick:1},
  {text:"Si viajara al pasado, ¿que llevaría para convencer a la gente de que soy un hechicero poderoso?",pick:1},
  {text:"Llame ya para adquirir un _. Nuestras operadoras esperan su llamada.",pick:1},
  {text:"El viaje escolar quedó totalmente arruinado por _.",pick:1},
  {text:"¿Cuál es el mejor amigo de una mujer?",pick:1},
  {text:"Doctor Corazón, estoy teniendo problemas con _ y quisiera su consejo.",pick:1},
  {text:"Cuando sea Presidente de México, crearé la Secretaría de _.",pick:1},
  {text:"¿Qué es lo que me ocultan mis papás?",pick:1},
  {text:"¿Qué es lo que nunca falla para animar las fiestas?",pick:1},
  {text:"En un mundo asolado por _, nuestro único consuelo es _.",pick:2},
  {text:"Haz un haiku.",pick:3},
  {text:"En una nueva película de M. Night Shyamalan, Bruce Willis descubre que _ en realidad siempre ha sido _.",pick:2},
  {text:"¿Qué mejora con la edad?",pick:1},{text:"_ es bueno hasta la última gota.",pick:1},
  {text:"Ojalá no hubiera perdido el manual de _.",pick:1},
  {text:"_. ¡Es una emboscada! (It's a trap!)",pick:1},
  {text:"El nuevo reality de MTV se trata de 8 celebridades fracasadas viviendo con _.",pick:1},
  {text:"¿Qué cosa le parecería perturbadora pero extrañamente encantadora a la abuela?",pick:1},
  {text:"¿Qué es lo más emo?",pick:1},{text:"No entendía bien _ hasta que me topé con _.",pick:2},
  {text:"Mientras tengo sexo, me gusta pensar en _.",pick:1},
  {text:"¿Qué hizo que terminara mi relación anterior?",pick:1},{text:"¿Qué es ese sonido?",pick:1},
  {text:"_. Así es como quiero morir.",pick:1},{text:"¿Porqué estoy pegajoso?",pick:1},
  {text:"¿Cuál es el siguiente juguete de la cajita feliz?",pick:1},
  {text:"¿De que cosa hay demasiado en el cielo?",pick:1},
  {text:"No se con que armas se peleará en la Tercera Guerra Mundial, pero la Cuarta Guerra Mundial se peleará con _.",pick:2},
  {text:"¿Qué funciona siempre para ligar?",pick:1},
  {text:"Se dice que el plato favorito de Vicente Fox es _ relleno de _.",pick:2},
  {text:"La Rosa de Guadalupe presenta: _, la historia de _.",pick:2},
  {text:"_: preferido por los niños, aprobado por las mamás.",pick:1},
  {text:"¿Porqué no puedo dormir en la noche?",pick:1},{text:"¿A que huele?",pick:1},
  {text:"¿Qué ayuda a que Felipe Calderón se relaje?",pick:1},
  {text:"El mundo se va a acabar, el mundo se va a acabar, _ es lo que nos va a matar.",pick:1},
  {text:"Próximamente, _: El Musical.",pick:1},
  {text:"Los antropólogos han descubierto una tribu primitiva que venera _.",pick:1},
  {text:"Antes de matarlo, Sr. Bond, déjeme mostrarle _.",pick:1},
  {text:"Estudios revelan que las ratas encuentran la salida de un laberinto 50% más rápido despues de ser expuestas a _.",pick:1},
  {text:"¿Cuál será la próxima pareja de superhéroes?",pick:2},
  {text:"A continuación en ESPN2: El Campeonato Mundial de _.",pick:1},
  {text:"Cuando sea billonario, construiré una estatua de 20 metros que conmemore _.",pick:1},
  {text:"Para atraer más visitantes, el Museo Smithsoniano de Ciencias Naturales ha abierto una exhibición interactiva de _.",pick:1},
  {text:"¡Guerra! ¿Para que sirve?",pick:1},{text:"¿Qué hace que me llene de gases?",pick:1},
  {text:"¿A que huelen los viejitos?",pick:1},
  {text:"¿Qué estoy dispuesto a sacrificar para la cuaresma?",pick:1},
  {text:"La medicina alternativa ahora utiliza los poderes curativos de _.",pick:1},
  {text:"¿Con que ayudan a las comunidades tarahumaras?",pick:1},
  {text:"¿Qué es lo que prefiere Carlos Salinas?",pick:1},
  {text:"Durante su poco conocido Periodo Café, Picasso produjo cientos de pinturas de _.",pick:1},
  {text:"¿Qué no quisieras encontrarte en tu comida china?",pick:1},
  {text:"Yo tomo para olvidar _.",pick:1},{text:"_. ¡Chócalas cuate!",pick:1},
  // === CARTAS NEGRAS EXTRA MODERNAS ===
  {text:"Lo último que quieres ver después de una peda es _.",pick:1},
  {text:"El nuevo sabor de Maruchan es _.",pick:1},{text:"México ganó el mundial gracias a _.",pick:1},
  {text:"La nueva serie de Netflix México se llama: '_: sin censura'.",pick:1},
  {text:"Lo que realmente pasa en los baños del antro es _.",pick:1},
  {text:"Mi mamá me cachó haciendo _ y no me habló por una semana.",pick:1},
  {text:"El verdadero secreto de los tacos al pastor es _.",pick:1},
  {text:"Si México fuera una persona, su biografía se llamaría: '_'.",pick:1},
  {text:"En mi próxima vida quiero reencarnar en _.",pick:1},
  {text:"Lo que tu uber piensa de ti cuando te sube a las 3am: _.",pick:1},
  {text:"La IA va a reemplazar muchas cosas, pero nunca podrá reemplazar _.",pick:1},
  {text:"Lo peor de ser godín es _.",pick:1},
  {text:"El nuevo trend de TikTok es grabarte mientras _.",pick:1},
  {text:"Según mi terapeuta, todos mis problemas vienen de _.",pick:1},
  {text:"México sería primer mundo si no fuera por _.",pick:1},
];

export const STARTER_CHALLENGES = [
  "El último en ir al baño","El más pedo del grupo","El último en echarse un pedo",
  "El primero en tomarse una chela hoy","El que tenga el ex más tóxico",
  "El que haya comido tacos más recientemente","El más chaparrito",
  "El que tenga más memes guardados","El que se haya bañado al último","El más crudo",
  "El que tenga la pila del celular más baja","El que deba más dinero",
  "El que haya stalkeado a su ex más recientemente","El más dramático del grupo",
  "El que haya llegado tarde hoy","El que ronque más fuerte",
  "El más intenso en el grupo de WhatsApp","El que peor cocine",
  "El que más audios largos mande","El que peor baile",
  "El que más se queje del calor","El último en publicar una historia",
  "El que tenga la pantalla del celular más rota","El más codo del grupo",
  "El que haya dicho la peor mentira esta semana",
];

// El castigo escala con el número de ronda
export function getPunishment(roundNum) {
  const light = [
    {text:"Toma {s} segundos 🍺", minS:1, maxS:3},
    {text:"Un traguito de {s} segundos, no pasa nada 😏", minS:1, maxS:2},
    {text:"Sorbo de {s} segundos, va suave 🍻", minS:1, maxS:3},
    {text:"Castigo ligero: {s} segundos a tu bebida 🥤", minS:2, maxS:3},
    {text:"Le das un trago de {s} segundos, tranqui 😌", minS:1, maxS:3},
  ];
  const medium = [
    {text:"Toma {s} segundos seguidos sin parar 🍺", minS:3, maxS:6},
    {text:"Dale {s} segundos a tu bebida y di algo vergonzoso 😳🍺", minS:3, maxS:5},
    {text:"Trago de {s} segundos + imita al que va ganando 🎭🍺", minS:4, maxS:6},
    {text:"{s} segundos de trago mientras el grupo cuenta en voz alta 📣🍺", minS:3, maxS:6},
    {text:"Piedra, papel o tijeras con el de tu derecha. Pierdes: {s} segundos. Ganas: él toma {s} segundos ✊🍺", minS:3, maxS:5},
    {text:"Trago de {s} segundos con los ojos cerrados 🙈🍺", minS:3, maxS:5},
  ];
  const heavy = [
    {text:"¡FONDO de {s} segundos sin respirar! 🫗", minS:5, maxS:10},
    {text:"Cascada: tomas {s} segundos y nadie puede parar hasta que tú pares 🌊", minS:5, maxS:8},
    {text:"Coctel sorpresa: cada jugador le agrega algo a tu vaso + {s} segundos de fondo 🍹💀", minS:5, maxS:10},
    {text:"Shot + {s} segundos de perseguidor. Sin hacer cara 😐🥃", minS:5, maxS:8},
    {text:"El grupo te sirve lo que quiera: {s} segundos de castigo 🍻💀", minS:6, maxS:10},
    {text:"Waterfall: tomas {s} segundos sin parar mientras el de tu derecha te echa porras 📣🍺", minS:7, maxS:10},
  ];
  let pool;
  if (roundNum <= 4) pool = light;
  else if (roundNum <= 9) pool = [...light, ...medium];
  else pool = [...medium, ...heavy];
  const pick = pool[Math.floor(Math.random() * pool.length)];
  const secs = Math.floor(Math.random() * (pick.maxS - pick.minS + 1)) + pick.minS;
  return { text: pick.text.replace(/\{s\}/g, secs), secs };
}

// Fisher-Yates shuffle
export function shuffle(a) {
  const b = [...a];
  for (let i = b.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [b[i], b[j]] = [b[j], b[i]];
  }
  return b;
}
